name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1a"
      TF_CLI_ARGS: "-input=false -auto-approve"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and extract Terraform
      run: |
        mkdir -p $HOME/terraform
        curl -Lo $HOME/terraform/terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
        unzip -d $HOME/terraform $HOME/terraform/terraform.zip
        echo "export PATH=\$PATH:$HOME/terraform" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Terraform Init
      run: terraform init -upgrade=true -backend=false

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply 

    - name: Notify on failure
      if: failure()
      run: echo "Terraform deployment failed. Check the workflow logs for details."




