name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1a"
      TF_CLI_ARGS: "-input=false -auto-approve"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and extract Terraform
      run: |
       curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
        unzip terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/
        terraform --version

    - name: Terraform Init
      run: terraform init $TF_CLI_ARGS -backend=false


    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply 

    - name: Notify on failure
      if: failure()
      run: echo "Terraform deployment failed. Check the workflow logs for details."




